export const projectsData = [
    {
        id: 1,
        title: 'ЖК Северная Звезда',
        slug: 'severnaya-zvezda',
        zone: 'moscow',
        propertyType: 'flat',
        complete: false,
        deadlineYear: 2025,
        price: 8500000,
        description: 'Современный жилой комплекс в Москве',
        location: 'Москва, САО',
        image_display: '/images/zvezda.png',
        name: 'ЖК Северная Звезда',
        address: 'Москва, САО',
    },
    {
        id: 2,
        title: 'ЖК Петроградский',
        slug: 'petrogradskiy',
        zone: 'spb',
        propertyType: 'flat',
        complete: true,
        deadlineYear: 2024,
        price: 12000000,
        description: 'Элитный комплекс в Санкт-Петербурге',
        location: 'СПб, Петроградский район',
        image_display: '/images/petro.png',
        name: 'ЖК Петроградский',
        address: 'СПб, Петроградский район',
    },
    {
        id: 3,
        title: 'Парковка Центральная',
        slug: 'parkovka-centralnaya',
        zone: 'moscow',
        propertyType: 'parking',
        complete: true,
        deadlineYear: 2023,
        price: 1500000,
        description: 'Подземная парковка в центре',
        location: 'Москва, ЦАО',
        image_display: '/images/parkovkams.png',
        name: 'Парковка Центральная',
        address: 'Москва, ЦАО',
    },
    {
        id: 4,
        title: 'ЖК Краснодар Сити',
        slug: 'krasnodar-city',
        zone: 'krasnodar',
        propertyType: 'flat',
        complete: false,
        deadlineYear: 2026,
        price: 6500000,
        description: 'Жилой комплекс в Краснодаре',
        location: 'Краснодар, Центр',
        image_display: '/images/krasnodarci.png',
        name: 'ЖК Краснодар Сити',
        address: 'Краснодар, Центр',
    },
    {
        id: 5,
        title: 'Кладовые Екатеринбург',
        slug: 'skladovye-ekaterinburg',
        zone: 'ekt',
        propertyType: 'storage',
        complete: true,
        deadlineYear: 2024,
        price: 800000,
        description: 'Кладовые помещения',
        location: 'Екатеринбург',
        image_display: '/images/klad.png',
        name: 'Кладовые Екатеринбург',
        address: 'Екатеринбург',
    },
];
